buslog:
  replicaCount: 2
  image:
    repository: quay.io/codefresh_sa/buslog
    tag: "8831e0d"
ctrlr:
  replicaCount: 2
  image:
    repository: quay.io/codefresh_sa/ctrlr
    tag: "2642d92"
flask-ui:
  replicaCount: 3
  image:
    repository: quay.io/codefresh_sa/flask-ui
    tag: "d8e8044"

# tag: 13b7cb2
# tag: 696b07f
# tag: 5c41d13
# tag: 7abe01c
# tag: 310ce88
# tag: ada05da
