buslog:
  replicaCount: 2
  image:
    repository: quay.io/codefresh_sa/buslog
    tag: "9179db7"
ctrlr:
  replicaCount: 2
  image:
    repository: quay.io/codefresh_sa/ctrlr
    tag: "65faca9"
flask-ui:
  replicaCount: 3
  image:
    repository: quay.io/codefresh_sa/flask-ui
    tag: "2d4e409"

# tag: 13b7cb2
# tag: 696b07f
# tag: 5c41d13
# tag: 7abe01c
# tag: 310ce88
# tag: ada05da
